### ISSUE TITLE
Review Needed

### ISSUE THREAD

**Issue by BernierMaxence** [PolytechLyon/isi3-tp2-visiteur-chabrier-bernier-tp2#1]

**Comment by BernierMaxence** [comment]
Bonjour, 

Avez-vous vu notre demande de review ? 

Bonne journée,

Maxence

**Comment by Slashgear** [comment]
j'y travaille 👷

**Comment by Slashgear** [comment]
- Good Job le rapport, vous semblez avoir bien compris le pattern

- Un petit nettoyage des variables OpG etc etc

- Et si on rangeait en packages (⚠️  les packages en java, c'est en minuscule)

**Comment by Eriwyr** [comment]
Merci pour votre réponse :) 
Les modifications demandées ont été apportées. 
Vous pouvez review le code.
Merci d'avance 
@Slashgear
